Mongo:
    Services:
        Todo:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Host: 192.168.58.20:27017
                Database: Todo
    Driver: \Webiny\Component\Mongo\Driver\Mongo
    ResultClass: \Webiny\Component\Mongo\MongoResult