Rest:
    TodoServices:
        CompilePath: /var/www/projects/todo/App/Cache/Rest
        Router:
            Class: \Todo\Modules\{module}\RestServices\{service}
            Path: /api/{module}/{service}
            Normalize: true
        Environment: development