Rest:
    TodoServices:
        CompilePath: ../App/Cache/Rest
        Router:
            Class: \Todo\Modules\{module}\RestServices\{service}
            Path: /api/{module}/{service}
            Normalize: false
        Environment: development