Security:
    Tokens:
        TodoToken:
            Driver: \Webiny\Component\Security\Token\CryptDrivers\Crypt\Crypt
            Params: [Cookie]
            SecurityKey: $3cR3tK3y_ToDo!$
    Encoders:
        CryptEncoder:
            Driver: \Webiny\Component\Security\Encoder\Drivers\Crypt
            Params: [Password]
            Salt: todoSalt
    UserProviders:
        BuiltInProvider:
            admin: {password: '$2y$08$bVxuLUGbeMCYGMBtJYU8Z.h4CNEAZaWKwoBnCiYv0qEj3IIaYiLcq', roles: ROLE_ADMIN}
        FromDatabase:
            Driver: \Webiny\Component\Security\User\Providers\Entity\Entity
            Params:
                Entity: Todo\Modules\Users\Models\User
                Username: username
                Password: password
                Role: ROLE_USER
    AuthenticationProviders:
        Form:
            Driver: \Webiny\Component\Security\Authentication\Providers\Form\Form
    Firewalls:
        Admin:
            RealmName: Administration
            Anonymous: true
            RememberMe: false
            Encoder: CryptEncoder
            Token: TodoToken
            UserProviders: [BuiltInProvider, FromDatabase]
            AuthenticationProviders: [Form]
            AccessControl:
                Rules:
                    - {Path: '/^\/login/', Roles: 'ROLE_ANONYMOUS'}
                    - {Path: '/^\/users/', Roles: 'ROLE_ADMIN'}
                    - {Path: '/^\/todo-list/*', Roles: 'ROLE_USER'}
            RoleHierarchy:
                ROLE_USER: ROLE_ANONYMOUS
                ROLE_ADMIN: ROLE_USER