TemplateEngine:
    Engines:
        Smarty:
            ForceCompile: false
            CacheDir: ../App/Cache/Smarty/Cache
            CompileDir: ../App/Cache/Smarty/Compile
            TemplateDir: ../App/Layouts
            AutoEscapeOutput: false