TemplateEngine:
    Engines:
        Smarty:
            ForceCompile: false
            CacheDir: '/var/www/projects/todo/App/Cache/Smarty/Cache'
            CompileDir: '/var/www/projects/todo/App/Cache/Smarty/Compile'
            TemplateDir: '/var/www/projects/todo/App/Layouts'
            AutoEscapeOutput: false