<?php

/**
 * This is an auto generated file by Webiny Rest component.
 * Please do not edit this file because the changes might break your REST Api.
 *
 * @rest.class \Todo\Modules\TodoList\RestServices\Item
 * @rest.version v1.0
 * @rest.aliasVersion current
 * @rest.url |url|
 * @rest.buildDate Mon, 12. Jan, 2015 20:40:47
 */

$a = include "../App/Cache/Rest/TodoServices/Todo_Modules_TodoList_RestServices_Item/v1.0.php";


return $a;