<?php

/**
 * This is an auto generated file by Webiny Rest component.
 * Please do not edit this file because the changes might break your REST Api.
 *
 * @rest.class \Todo\Modules\TodoList\RestServices\Item
 * @rest.version v1.0
 * @rest.buildDate Wed, 17. Dec, 2014 04:11:13
 */

$a = array (
  'class' => '\\Todo\\Modules\\TodoList\\RestServices\\Item',
  'cacheKeyInterface' => false,
  'accessInterface' => false,
  'version' => '1.0',
  'post' => 
  array (
    'create-task/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'createTask',
      'urlPattern' => 'create-task',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 201,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
      ),
    ),
  ),
  'get' => 
  array (
    'toggle-status/([\\w-]+)/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'toggleStatus',
      'urlPattern' => 'toggle-status',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 200,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
        'id' => 
        array (
          'required' => true,
          'type' => 'string',
          'default' => NULL,
        ),
      ),
    ),
    'delete-task/([\\w-]+)/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'deleteTask',
      'urlPattern' => 'delete-task',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 200,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
        'id' => 
        array (
          'required' => true,
          'type' => 'string',
          'default' => NULL,
        ),
      ),
    ),
    'http-request/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'httpRequest',
      'urlPattern' => 'http-request',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 200,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
      ),
    ),
    'http-cookie/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'httpCookie',
      'urlPattern' => 'http-cookie',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 200,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
      ),
    ),
    'http-session/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'httpSession',
      'urlPattern' => 'http-session',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 200,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
      ),
    ),
    'http-response/([\\w-]+)/([\\d]+)/([\\w-]+)/' => 
    array (
      'default' => false,
      'role' => false,
      'method' => 'httpResponse',
      'urlPattern' => 'http-response',
      'cache' => 
      array (
        'ttl' => 0,
      ),
      'header' => 
      array (
        'cache' => 
        array (
          'expires' => 0,
        ),
        'status' => 
        array (
          'success' => 200,
          'error' => 404,
          'errorMessage' => '',
        ),
      ),
      'rateControl' => 
      array (
      ),
      'params' => 
      array (
        'content' => 
        array (
          'required' => true,
          'type' => 'string',
          'default' => '',
        ),
        'statusCode' => 
        array (
          'required' => false,
          'type' => 'integer',
          'default' => 200,
        ),
        'headers' => 
        array (
          'required' => true,
          'type' => 'string',
          'default' => 
          array (
          ),
        ),
      ),
    ),
  ),
);


return $a;