<?php

/**
 * This is an auto generated file by Webiny Rest component.
 * Please do not edit this file because the changes might break your REST Api.
 *
 * @rest.class \Todo\Modules\TodoList\RestServices\Test
 * @rest.version v1.0
 * @rest.aliasVersion latest
 * @rest.url |url|
 * @rest.buildDate Tue, 06. Jan, 2015 00:29:40
 */

$a = include "../App/Cache/Rest/TodoServices/Todo_Modules_TodoList_RestServices_Test/v1.0.php";


return $a;